### ISSUE TITLE
Question ?

### ISSUE THREAD

**Issue by Im-Goutham** [andreiduca/cra-ssr-code-splitting#5]
Can this code be used as a boilerplate for building frontend react applications ?

**Comment by andreiduca** [comment]
It _could_ be a starting point, but **please read the [`README.md`](https://github.com/andreiduca/cra-ssr-code-splitting#can-i-use-this-as-a-template-for-a-production-app)**. And make sure you read and understand what **security measures you have to implement** and take care of for your expressjs app. There are plenty of tutorials out there on the subject.
