### ISSUE TITLE
Babel 7

### ISSUE THREAD

**Issue by j2is** [andreiduca/cra-ssr-code-splitting#6]
Great repo, would be really good to update the babel requirements for Babel 7 (things like @babel/register instead of babel-register etc.

**Comment by andreiduca** [comment]
I think you missed it, but the repo is already using Babel 7: https://github.com/andreiduca/cra-ssr-code-splitting/blob/master/server/bootstrap.js
I haven't updated the articles tho.

**Comment by j2is** [comment]
Thanks, should it not be using preset-emv?

**Comment by andreiduca** [comment]
You mean this? `presets: ['@babel/preset-env', '@babel/preset-react']`

**Comment by j2is** [comment]
Hey yes, never mind I see it was updated already! Ignore me. Thank you
